name: Deploy to AWS

on:
  push:
    branches:
      - main  # Change this if your default branch is different
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Change this if your AWS region is different

      - name: Deploy using SSH
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_HOST }} << 'EOF'
            cd /var/www/html  # Change this to your deployment directory
            git pull origin main  # Pull latest changes
            npm install  # Install dependencies if using Node.js
            pm2 restart all  # Restart app if using PM2
          EOF
